### Get all items
GET http://127.0.0.1:3000/api/items
Content-Type: application/json

###

### Add new item
POST http://127.0.0.1:3000/api/items
Content-Type: application/json

{
  "name": "Espresso",
  "price": 3.0
}

###

### Update item
PUT http://127.0.0.1:3000/api/items/1
Content-Type: application/json

{
  "price": 3.8
}

###

### Delete item
DELETE http://127.0.0.1:3000/api/items/2
Content-Type: application/json

###

### Get summary
GET http://127.0.0.1:3000/api/summary
